import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function POST(req: Request) {
    try {
        const { content, filename = 'generated-workflow' } = await req.json();

        if (!content) {
            return NextResponse.json({ ok: false, error: 'Content is required' }, { status: 400 });
        }

        // Clean filename: remove .md if present, replace spaces with dashes, etc.
        const cleanName = filename.replace(/\.md$/, '').replace(/[^a-z0-9_\u4e00-\u9fa5]/gi, '-').toLowerCase();

        // Ensure uniquely named file if needed, but for now we trust the user or use a timestamp
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
        const finalFilename = `${cleanName}-${timestamp}.md`;

        // Path to .agents/workflows
        // Note: In Next.js, process.cwd() is project root.
        const workflowDir = path.join(process.cwd(), '.agents', 'workflows');

        // Ensure directory exists
        if (!fs.existsSync(workflowDir)) {
            fs.mkdirSync(workflowDir, { recursive: true });
        }

        const filePath = path.join(workflowDir, finalFilename);

        // Add Frontmatter
        const workflowContent = `---
description: ${filename} (Generated by AI)
---
${content}`;

        fs.writeFileSync(filePath, workflowContent, 'utf8');

        return NextResponse.json({
            ok: true,
            message: 'Workflow generated successfully',
            path: filePath,
            filename: finalFilename
        });

    } catch (error: any) {
        console.error('❌ [Generate Workflow API] Error:', error);
        return NextResponse.json({ ok: false, error: error.message }, { status: 500 });
    }
}
