"use client";

import { WhiteWebSdk, Room } from "white-web-sdk";
import { useEffect, useRef, useState } from "react";
import { DataStore } from "@aws-amplify/datastore";
// Models are generated by `amplify codegen models` into a `models` module.
// Load them dynamically at runtime so the Next.js build won't fail if
// codegen hasn't been run in the environment where the build happens.

const AgoraWhiteboard = ({ channelName }: { channelName: string }) => {
  const whiteboardEl = useRef<HTMLDivElement>(null);
  const [room, setRoom] = useState<Room | null>(null);

  useEffect(() => {
    let subscription: any | undefined;

    const joinWhiteboardRoom = async () => {
      try {
        const whiteWebSdk = new WhiteWebSdk({
          appIdentifier: process.env.NEXT_PUBLIC_AGORA_APP_ID!,
          region: "us-sv",
        });

        // Try to load generated models (may not exist if `amplify codegen models` hasn't been run)
        let WhiteboardEventModel: any = null;
        try {
          // Types for the generated models may not exist in this environment.
          // @ts-ignore: dynamic import of generated models (may be absent)
          const models = await import("../models");
          WhiteboardEventModel = models.WhiteboardEvent;
        } catch (err) {
          console.warn("Amplify models not found. Skip DataStore sync. Run `amplify codegen models` to enable.", err);
        }

        // Fetch historical events (only if model is available)
        let historicalEvents: any[] | undefined = undefined;
        if (WhiteboardEventModel) {
          historicalEvents = await DataStore.query(WhiteboardEventModel, (c: any) =>
            c.channel.eq(channelName)
          );
        }

        // You'll need a way to get a token. For now, we'll focus on the datastore logic.
        // This part of the code needs to be adapted to your token generation logic.
        // For simplicity, we are assuming a token is available.
        // In a real application, you would fetch this from your backend.
        const roomToken = "your_room_token"; // Replace with actual token generation

        // Cast to any to avoid strict SDK type mismatch during build
        const newRoom = await (whiteWebSdk as any).joinRoom({
          uuid: channelName,
          roomToken: roomToken,
          isWritable: true,
        } as any);

        // Replay historical events
        historicalEvents?.forEach((event) => {
          (newRoom as any).dispatchMagixEvent?.(event.event);
        });

        if (whiteboardEl.current) {
          newRoom.bindHtmlElement(whiteboardEl.current);
        }

        setRoom(newRoom);

        // Listen for local events and save to DataStore (only if model available)
        if (WhiteboardEventModel) {
          (newRoom as any).callbacks.on("onMagixEvent", (event: any) => {
            DataStore.save(
              new WhiteboardEventModel({
                channel: channelName,
                event: event,
                timestamp: new Date().getTime(),
              })
            ).catch((e: any) => console.warn("DataStore.save failed:", e));
          });

          // Subscribe to new events from DataStore
          subscription = DataStore.observe(WhiteboardEventModel, (c: any) =>
            c.channel.eq(channelName)
          ).subscribe((msg: any) => {
            if (msg && msg.opType === "CREATE") {
              (newRoom as any).dispatchMagixEvent?.(msg.element?.event);
            }
          });
        }

      } catch (error) {
        console.error("Failed to join whiteboard room:", error);
      }
    };

    joinWhiteboardRoom();

    return () => {
      if (room) {
        room.disconnect();
      }
      if (subscription) {
        subscription.unsubscribe();
      }
    };
  }, [channelName]);

  return <div ref={whiteboardEl} style={{ width: "100%", height: "600px", border: "1px solid #ccc" }} />;
};

export default AgoraWhiteboard;