"use client";

import { WhiteWebSdk, Room } from "white-web-sdk";
import { useEffect, useRef, useState } from "react";
import { DataStore } from "aws-amplify";
import { WhiteboardEvent } from "../models"; // This will be generated by `amplify codegen models`

const AgoraWhiteboard = ({ channelName }: { channelName: string }) => {
  const whiteboardEl = useRef<HTMLDivElement>(null);
  const [room, setRoom] = useState<Room | null>(null);

  useEffect(() => {
    let subscription: ZenObservable.Subscription | undefined;

    const joinWhiteboardRoom = async () => {
      try {
        const whiteWebSdk = new WhiteWebSdk({
          appIdentifier: process.env.NEXT_PUBLIC_AGORA_APP_ID!,
          region: "us-sv",
        });

        // Fetch historical events
        const historicalEvents = await DataStore.query(WhiteboardEvent, (c) =>
          c.channel.eq(channelName)
        );

        // You'll need a way to get a token. For now, we'll focus on the datastore logic.
        // This part of the code needs to be adapted to your token generation logic.
        // For simplicity, we are assuming a token is available.
        // In a real application, you would fetch this from your backend.
        const roomToken = "your_room_token"; // Replace with actual token generation

        const newRoom = await whiteWebSdk.joinRoom({
          uuid: channelName,
          roomToken: roomToken,
          isWritable: true,
        });

        // Replay historical events
        historicalEvents.forEach((event) => {
          newRoom.dispatchMagixEvent(event.event);
        });

        if (whiteboardEl.current) {
          newRoom.bindHtmlElement(whiteboardEl.current);
        }

        setRoom(newRoom);

        // Listen for local events and save to DataStore
        newRoom.callbacks.on("onMagixEvent", (event) => {
          DataStore.save(
            new WhiteboardEvent({
              channel: channelName,
              event: event,
              timestamp: new Date().getTime(),
            })
          );
        });

        // Subscribe to new events from DataStore
        subscription = DataStore.observe(WhiteboardEvent, (c) =>
          c.channel.eq(channelName)
        ).subscribe((msg) => {
          if (msg.opType === "CREATE") {
            newRoom.dispatchMagixEvent(msg.element.event);
          }
        });

      } catch (error) {
        console.error("Failed to join whiteboard room:", error);
      }
    };

    joinWhiteboardRoom();

    return () => {
      if (room) {
        room.disconnect();
      }
      if (subscription) {
        subscription.unsubscribe();
      }
    };
  }, [channelName]);

  return <div ref={whiteboardEl} style={{ width: "100%", height: "600px", border: "1px solid #ccc" }} />;
};

export default AgoraWhiteboard;