
"use client";

import { Amplify } from "aws-amplify";
import awsExports from "../aws-exports"; // This file will be generated by the Amplify CLI

// aws-exports types may not include the `ssr` flag; cast to `any` to avoid
// TypeScript errors in environments where the generated typings differ.
Amplify.configure({ ...(awsExports as any), ssr: true } as any);

export default function ConfigureAmplify() {
  return null;
}
