
"use client";

import { Amplify } from "aws-amplify";
import awsExports from "../aws-exports"; // This file will be generated by the Amplify CLI

Amplify.configure({ ...awsExports, ssr: true });

export default function ConfigureAmplify() {
  return null;
}
