import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

const apiRegistryPath = path.join(projectRoot, 'docs', 'api_registry.md');

function getNextJsApis() {
    const apis = [];
    const apiDir = path.join(projectRoot, 'app', 'api');

    function walk(dir) {
        if (!fs.existsSync(dir)) return;
        const files = fs.readdirSync(dir);
        for (const file of files) {
            const filePath = path.join(dir, file);
            const stat = fs.statSync(filePath);
            if (stat.isDirectory()) {
                walk(filePath);
            } else if (file === 'route.ts' || file === 'route.js') {
                const content = fs.readFileSync(filePath, 'utf-8');
                const relativePath = path.relative(apiDir, dir).replace(/\\/g, '/');
                const methods = [];
                const possibleMethods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS'];
                
                for (const method of possibleMethods) {
                    if (new RegExp(`export (async )?function ${method}`).test(content) || 
                        new RegExp(`export const ${method} =`).test(content)) {
                        methods.push(method);
                    }
                }
                
                apis.push({
                    type: 'Next.js',
                    path: `/api/${relativePath}`,
                    methods,
                    file: path.relative(projectRoot, filePath).replace(/\\/g, '/')
                });
            }
        }
    }

    walk(apiDir);
    return apis;
}

function getFastApiApis() {
    const apis = [];
    const pythonFiles = ['main.py']; // Can add more if needed
    
    for (const file of pythonFiles) {
        const filePath = path.join(projectRoot, file);
        if (!fs.existsSync(filePath)) continue;
        
        const content = fs.readFileSync(filePath, 'utf-8');
        const lines = content.split('\n');
        
        for (let i = 0; i < lines.length; i++) {
            const line = lines[i];
            const match = line.match(/@app\.(get|post|put|delete|patch|options|head)\("([^"]+)"\)/);
            if (match) {
                const method = match[1].toUpperCase();
                const apiPath = match[2];
                
                apis.push({
                    type: 'FastAPI',
                    path: apiPath,
                    methods: [method],
                    file: file
                });
            }
        }
    }
    return apis;
}

function generateMarkdown(apis) {
    let md = '# 🚀 API Registry\n\n';
    md += 'This file is automatically generated and updated to track all APIs in the project.\n\n';
    md += '| Type | Method | Path | Source File |\n';
    md += '| :--- | :--- | :--- | :--- |\n';
    
    // Sort by path
    const sortedApis = apis.sort((a, b) => a.path.localeCompare(b.path));
    
    for (const api of sortedApis) {
        for (const method of api.methods) {
            md += `| ${api.type} | **${method}** | \`${api.path}\` | [${api.file}](file:///${path.join(projectRoot, api.file).replace(/\\/g, '/')}) |\n`;
        }
    }
    
    md += `\n*Last updated: ${new Date().toISOString()}*\n`;
    return md;
}

const allApis = [...getNextJsApis(), ...getFastApiApis()];
const markdown = generateMarkdown(allApis);

if (!fs.existsSync(path.join(projectRoot, 'docs'))) {
    fs.mkdirSync(path.join(projectRoot, 'docs'));
}

fs.writeFileSync(apiRegistryPath, markdown);
console.log(`API Registry updated at ${apiRegistryPath}`);
console.log(`Found ${allApis.length} API routes.`);
